### ISSUE TITLE
Logical issues

### ISSUE THREAD

**Issue by justin-prabhakaran** [justin-prabhakaran/homies.marksystem#11]
Some the following issues are needed to be resolved,

**1. Mark should be less than 100 and greater than 0.  `0 <= mark <= 100`**

**2. Rank should not be provided to those who scores under 35 marks. It should be denoted as `No Rank`** 

_Sample_
```java
 Mark m = st.getMarks();
            if (m.getMark1() < 30 || m.getMark2() < 30 || m.getMark3() < 30 || m.getMark4() < 30 || m.getMark5() < 30 || m.getMark6() < 30) {
                tablePrinter.addRow(st.getName(), ToString(st.getMarks().getTotal()), "No Rank",
                        st.getMarks().advice());
            } else {
                tablePrinter.addRow(st.getName(), String.valueOf(st.getMarks().getTotal()), String.valueOf(rank),
                        st.getMarks().advice());
            }
``` 
**3. The sorting in table must be based on rank of each student and not based on total mark of that students because the may have greater total mark but failed in some subject**

**Comment by justin-prabhakaran** [comment]
Please resolve this as soon as possible!! Because tomorrow is the last day.

**Comment by Vjkumar2004** [comment]
1 --> problem solved✅

**Comment by Vjkumar2004** [comment]
2 --> problem solved✅

**Comment by Vjkumar2004** [comment]
3 --> problem solved✅
